name: snake
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  intl: ^0.17.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: LetoTextSans
      fonts:
        - asset: assets/fonts/LetoTextSans/LetoTextSansDefect.otf
